apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: no-pvc
spec:
  serviceName: no-pvc
  replicas: 1
  selector:
    matchLabels:
      app: no-pvc
  template:
    metadata:
      labels:
        app: no-pvc
    spec:
      containers:
      - image: okteto/hello-world:golang
        name: c1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
        - name: no-pvc
          persistentVolumeClaim:
            claimName: no-pvc
